spring.application.name=taskManager

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
# Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
# JWT Configuration
jwt.secret=fIzPi8fd1MpxHbyL3J8UG4WmJVCTJoN6x964ujoQQDH
jwt.expiration=3600000
